# Return class & parent IDs and labels for all ancestors of a set of classes
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>
PREFIX oboInOwl: <http://www.geneontology.org/formats/oboInOwl#>
PREFIX DOID: <http://purl.obolibrary.org/obo/DOID_>

SELECT ?id ?label ?parent_id ?parent_label
WHERE {
	VALUES ?set { !<<values_set>>! }

	?iri ^rdfs:subClassOf* ?set ;
		oboInOwl:id ?id ;
		rdfs:label ?label ;
		rdfs:subClassOf ?parent_iri .
	
	?parent_iri oboInOwl:id ?parent_id ;
		rdfs:label ?parent_label .
}