#' Convert PubMed summary to tibble (DEPRECATED)
#'
#' Convert list result generated by [rentrez::entrez_summary()] from the
#' PubMed database into a tibble.
#'
#' @return A dataframe with `uid`, `pubdate`, `title`, and `fulljournalname`;
#' may also include `authors`, `authtype` and `auth_clusterid` if author
#' information is present and additional variables included with `addl_items`
#'
#' @section DEPRECATION NOTICE:
#' This function has been in favor of [tidy_pub_records()] and will not work on
#' `esummary_list` objects.
#'
#' @param pm_summary result from `rentrez::entrez_summary(db = "pubmed", ...)`
#' @param addl_items character vector listing "items" (_i.e._ data variables)
#' to include in tidy dataset beyond the default: uid, pubdate, title,
#' authors, fulljournalname
#'
#' @export
tidy_pubmed_summary <- function(pm_summary, addl_items = NULL) {
    rlang::inform("tidy_pubmed_summary() has been deprecated. Use tidy_pub_records().")

    details <- unique(
        c("uid", "pubdate", "title", "authors", "fulljournalname",
          addl_items)
    )

    summary_list <- rentrez::extract_from_esummary(pm_summary, details)

    if (rlang::is_empty(summary_list$authors)) {
        authors <- NULL
    } else {
        authors <- tidy_pubmed_authors(summary_list$authors)
    }

    summary_list$authors <- NULL
    summary_df <- dplyr::bind_cols(summary_list, authors)

    summary_df
}

# Collapses PubMed author dataframe to a single row
#
# Invariant column values are collapsed
# clusterid is dropped if it contains only blank values
tidy_pubmed_authors <- function(authors_df) {
    authors_tidy <- authors_df %>%
        dplyr::rename(authors = .data$name, auth_clusterid = .data$clusterid) %>%
        purrr::map_dfc(
            function(x) {
                unique_if_invariant(x) %>%
                    vctr_to_string()
            }
        )

    if (is_blank(authors_tidy$auth_clusterid)) {
        authors_tidy <- dplyr::select(.data$authors_tidy, -.data$auth_clusterid)
    }

    authors_tidy
}
