#' Parse Mapping
#'
#' Parses mappings generated by [pyobo_map()] or otherwise produced by the
#' python module [GILDA](https://gilda.readthedocs.io/en/latest/).
#'
#' @param py_gilda_res_list A named list of term mapping lists (see
#'     [parse_term_mapping()]), likely generated by [pyobo_map()].
#' @inheritDotParams extract_ScoredMatch -py_ScoredMatch
#' @inheritDotParams parse_term_mapping -py_gilda_term_mappings
#'
#' @returns
#' List of data frames with the mapping result(s) for each term.
#'
#' @export
parse_mapping <- function(py_gilda_res_list, ...) {
    parsed_list <- purrr::map(
        py_gilda_res_list,
        parse_term_mapping,
        ...
    )

    parsed_list
}


# parse_mapping() utils ---------------------------------------------------

#' Parse Mapping for Single Term (INTERNAL)
#'
#' Parses mappings generated by [pyobo_map()] or otherwise produced by the
#' python module [GILDA](https://gilda.readthedocs.io/en/latest/) AT THE
#' LEVEL of a single input term.
#'
#' @param py_gilda_term_mappings A list of mappings between a single input term
#'     and one or more namespace terms (stored as specialized `ScoredMatch`
#'     python objects, as defined by GILDA; see [extract_ScoredMatch]).
#' @param best_only Whether to return the best scoring result(s) only, as a
#'     boolean. `FALSE` will return all results. **NOTE:** `TRUE` will return
#'     more than one result in the case of ties.
#' @param warn_best_gt1 Whether to warn that best mapping ties exist for
#'     a term.
#' @inheritDotParams extract_ScoredMatch -py_ScoredMatch
#'
#' @returns
#' List of data frames with the mapping result(s) for each term.
#'
#' @keywords internal
parse_term_mapping <- function(py_gilda_term_mappings, best_only = TRUE,
                               warn_best_gt1 = FALSE, ...) {

    # produce empty tibble when no matches to term exist
    if (length(py_gilda_term_mappings) == 0) {
        return(
            tibble::tribble(
                ~id, ~term, ~score,
                NA, NA, NA
            )
        )
    }

    mapping <- purrr::map_dfr(py_gilda_term_mappings, extract_ScoredMatch, ...)

    if (best_only) {
        best_mapping <- mapping %>%
            dplyr::filter(.data$score == max(.data$score, na.rm = TRUE))
        if (warn_best_gt1) {
            warning(names(py_gilda_term_mappings), " has >1 best mapping.")
        }

        return(best_mapping)
    }

    mapping
}

#' Extract ScoredMatch Objects (INTERNAL)
#'
#' Extracts mapping results from specialized `ScoredMatch` python objects
#' (as defined by GILDA) AT THE LEVEL of individual mappings.
#'
#' @param py_ScoredMatch A GILDA ScoredMatch (python) object.
#' @param prefix _Optional_ prefix to add to namespace local unique identifiers
#'     (LUI; e.g. 4, the LUI for "disease" in DO), as a string; preferably to
#'     create a complete namespace ID (e.g. "DOID:4").
#' @param prefix_sep _Optional_ separator placed between `prefix` and
#'     namespace LUIs, as a string. Ignored if `prefix = NULL`.
#'
#' @keywords internal
extract_ScoredMatch <- function(py_ScoredMatch, prefix = NULL,
                                prefix_sep = ":") {
    if (is.null(prefix)) {
        prefix_sep <- NULL
    }

    df <- tibble::tibble(
        id = paste0(prefix, prefix_sep, py_ScoredMatch$term$id),
        term = py_ScoredMatch$term$entry_name,
        score = round(py_ScoredMatch$score, 2)
    )

    df
}


# parse_omim_name() -------------------------------------------------------

#' Parse OMIM Entry Names
#'
#' Parses OMIM entry names into case- and order-normalized names, preserving
#' abbreviations, if present.
#'
#' @param x A character vector of OMIM entry name strings.
#' @param eponyms A named character vector for proper noun (eponym)
#'   capitalization, where names are lowercase words and values are their
#'   capitalized replacements, e.g. `c("waardenburg" = "Waardenburg")`, or
#'   `NULL` to disable (default: [disease_eponyms]).
#' @param patterns A named character vector of phrase-level regex substitutions
#'   applied to the full lowercased name *after* `eponyms`, longest-first.
#'   Useful for context-sensitive capitalization, e.g.
#'   `c("short syndrome" = "SHORT syndrome")`, or `NULL` to disable (default:
#'   [disease_cap_patterns]).
#' @param qualifiers A character vector of uppercase OMIM qualifier tokens that
#'   force name rearrangement, in addition to the hardcoded structural patterns
#'   (numbers, `TYPE`, and definitive inheritance terms). Use `NULL` to disable
#'   adjective qualifier matching (default: [omim_qualifiers]).
#'
#' @details
#' Reverses OMIM\'s inverted filing convention by reclassifying comma-separated
#' qualifier tokens (inheritance terms, type codes, onset adjectives, etc.) and
#' reassembling them in natural-language order. Rearrangement is only applied
#' when at least one qualifier matches a recognized forcing pattern; otherwise
#' tokens are kept in original order and lowercased. See the
#' [algorithm article](https://allenbaron.github.io/DO.utils/articles/parse-omim-name.html)
#' for full details on qualifier classification, capitalization rules, and
#' known limitations.
#'
#' @returns A character vector of normalized OMIM entry names with
#' abbreviations preserved.
#'
#' @seealso [disease_eponyms] for the curated eponym replacement vector;
#'   [disease_cap_patterns] for the curated phrase pattern replacement vector;
#'   [omim_qualifiers] for the curated adjective qualifier vector;
#'   the [algorithm article](https://allenbaron.github.io/DO.utils/articles/parse-omim-name.html)
#'   for full details on how parsing and rearrangement work.
#'
#' @examples
#' omim_names <- c(
#'     "SCHIZOPHRENIA 12",
#'     "DYSTONIA 12; DYT12",
#'     "SPASTIC PARAPLEGIA 14, AUTOSOMAL RECESSIVE; SPG14",
#'     "OSTEOGENESIS IMPERFECTA, TYPE XI; OI11",
#'     "SCOLIOSIS, ISOLATED, SUSCEPTIBILITY TO, 1; IS1",
#'     "EPILEPSY, PROGRESSIVE MYOCLONIC, 4, WITH OR WITHOUT RENAL FAILURE; EPM4"
#' )
#'
#' parse_omim_name(omim_names)
#'
#' # Proper noun correction via custom eponyms (overrides disease_eponyms)
#' parse_omim_name(
#'     "PERIPHERAL DEMYELINATING NEUROPATHY, CENTRAL DYSMYELINATION, WAARDENBURG SYNDROME, AND HIRSCHSPRUNG DISEASE; PCWH",
#'     eponyms = c("waardenburg" = "Waardenburg", "hirschsprung" = "Hirschsprung")
#' )
#'
#' # Context-sensitive capitalization via phrase patterns (overrides eponyms)
#' parse_omim_name(
#'     "SHORT SYNDROME; SHORTSYN",
#'     patterns = c("short syndrome" = "SHORT syndrome")
#' )
#'
#' @export
parse_omim_name <- function(x, eponyms = disease_eponyms,
                            patterns = disease_cap_patterns,
                            qualifiers = omim_qualifiers) {
    if (!is.null(eponyms) && !is.character(eponyms)) {
        rlang::abort(
            "`eponyms` must be a named character vector or NULL.",
            call = rlang::caller_env()
        )
    }
    if (!is.null(patterns) && !is.character(patterns)) {
        rlang::abort(
            "`patterns` must be a named character vector or NULL.",
            call = rlang::caller_env()
        )
    }
    if (!is.null(qualifiers) && !is.character(qualifiers)) {
        rlang::abort(
            "`qualifiers` must be a character vector or NULL.",
            call = rlang::caller_env()
        )
    }

    parsed <- lapply(x, omim_parse_one, qualifiers = qualifiers)
    names_lower <- vapply(parsed, `[[`, character(1), "name")
    paste_na_rm(
        fix_disease_caps(names_lower, eponyms, patterns),
        vapply(parsed, `[[`, character(1), "abbreviation"),
        sep = "; "
    )
}


# parse_omim_name() internal helpers --------------------------------------

#' Parse a single OMIM entry name string (INTERNAL)
#' @noRd
omim_parse_one <- function(entry, qualifiers = omim_qualifiers) {
    entry <- trimws(entry)
    # Strip OMIM provisional phenotype-gene relationship marker
    entry <- sub("^\\?", "", entry)

    # extract optional abbreviation (after semicolon)
    parts <- strsplit(entry, "\\s*;\\s*")[[1L]]
    name_raw <- toupper(parts[1L])
    abbreviation <- if (length(parts) < 2L || nchar(parts[2L]) == 0L) {
        NA_character_
    } else {
        parts[2L]
    }

    tokens <- trimws(strsplit(name_raw, ",\\s*")[[1L]])

    if (length(tokens) == 1L) {
        std_nm <- tolower(tokens)
    } else {
        primary <- tokens[[1L]]
        remaining <- tokens[-1L]

        # rearrange if at least one qualifier matches a forcing pattern
        if (omim_has_forcing(remaining, qualifiers)) {
            std_nm <- omim_rearrange(primary, remaining)
        } else {
            std_nm <- paste(tokens, collapse = ", ")
        }
    }

    list(name = tolower(std_nm), abbreviation = abbreviation)
}


#' Check whether any qualifier tokens force rearrangement (INTERNAL)
#'
#' Rearrangement is triggered when at least one remaining (comma-separated)
#' qualifier matches a number, a TYPE qualifier, a definitive inheritance
#' pattern, or a core set of strong adjective qualifiers.
#' @noRd
omim_has_forcing <- function(tokens, qualifiers = omim_qualifiers) {
    structural <- grepl(
        paste0(
            # Pure number or alphanumeric subtype code, e.g. "1", "4", "7A"
            "^\\d+[A-Za-z]{0,2}$",
            # TYPE / MULTIPLE TYPES qualifier
            "|^(TYPE|MULTIPLE TYPES?)\\b",
            # Definitive inheritance qualifier (with optional trailing number)
            "|^(AUTOSOMAL (DOMINANT|RECESSIVE)|X-LINKED( (DOMINANT|RECESSIVE))?",
            "|Y-LINKED|MITOCHONDRIAL)( \\d+[A-Za-z]{0,2})?$"
        ),
        tokens
    )
    qual_match <- if (!is.null(qualifiers) && length(qualifiers) > 0L) {
        grepl(
            paste0("^(", paste(qualifiers, collapse = "|"), ")\\b"),
            tokens
        )
    } else {
        rep(FALSE, length(tokens))
    }
    any(structural | qual_match)
}


#' Rearrange OMIM inverted qualifier tokens into natural-language order
#' (INTERNAL)
#'
#' @returns A rearranged string with no effect on capitalization.
#'
#' @noRd
omim_rearrange <- function(primary, remaining) {
    # Token-type predicates (each operates on a single uppercase string)
    is_num <- function(x) grepl("^\\d+[A-Za-z]{0,2}$", x)
    is_type <- function(x) grepl("^(TYPE|MULTIPLE TYPES?)\\b", x)
    is_susc <- function(x) identical(x, "SUSCEPTIBILITY TO")
    is_trail <- function(x) grepl("^(WITH|WITHOUT|DUE TO|AND|OR)\\b", x)
    is_def <- function(x) {
        grepl(
            paste0(
                "^(AUTOSOMAL (DOMINANT|RECESSIVE)|X-LINKED( (DOMINANT|RECESSIVE))?",
                "|Y-LINKED|MITOCHONDRIAL)( \\d+[A-Za-z]{0,2})?$"
            ),
            x
        )
    }

    numbers <- character(0)
    type_quals <- character(0)
    left_pre <- character(0) # non-definitive pre-qualifiers (in order)
    right_pre <- character(0) # definitive pre-qualifiers (in order)
    trailing <- character(0)
    susceptibility <- FALSE
    in_trailing <- FALSE

    for (tok in remaining) {
        # Inside trailing phrase: collect tokens, pulling out any definitive
        # pre-qualifiers that OMIM lists *after* the trailing phrase
        # (e.g. "... AND DISTAL MOTOR NEUROPATHY, AUTOSOMAL DOMINANT").
        if (in_trailing) {
            if (is_def(tok)) {
                right_pre <- c(right_pre, tok)
            } else {
                trailing <- c(trailing, tok)
            }
            next
        }

        # Trailing phrase start
        if (is_trail(tok)) {
            in_trailing <- TRUE
            trailing <- c(trailing, tok)
            next
        }

        # SUSCEPTIBILITY TO
        if (is_susc(tok)) {
            susceptibility <- TRUE
            next
        }

        # Extract a number embedded at the end of a qualifier token,
        # e.g. "AUTOSOMAL RECESSIVE 117" → qualifier "AUTOSOMAL RECESSIVE"
        # + number "117".
        embedded <- regmatches(tok, regexpr("\\d+[A-Za-z]{0,2}$", tok))
        if (length(embedded) > 0L && !is_num(tok)) {
            tok_base <- trimws(sub("\\s*\\d+[A-Za-z]{0,2}$", "", tok))
            if (nchar(tok_base) > 0L) {
                numbers <- c(numbers, embedded)
                tok <- tok_base
            }
        }

        # Classify the (possibly stripped) token
        if (is_num(tok)) {
            numbers <- c(numbers, tok)
        } else if (is_type(tok)) {
            type_quals <- c(type_quals, tok)
        } else if (is_def(tok)) {
            right_pre <- c(right_pre, tok)
        } else {
            left_pre <- c(left_pre, tok)
        }
    }

    # Pre-qualifier order: definitive qualifiers (right_pre) first, then
    # non-definitive in REVERSE listing order — this matches the OMIM
    # preferred-name convention where the last listed qualifier appears first.
    all_pre <- c(right_pre, rev(left_pre))

    # Attach numbers/type-codes to primary, separated by a space.
    primary_part <- primary
    for (n in numbers) {
        primary_part <- paste(primary_part, n)
    }
    if (length(type_quals) > 0L) {
        primary_part <- paste(primary_part, paste(type_quals, collapse = " "))
    }

    # Assemble
    parts <- c(all_pre, primary_part)
    if (length(trailing) > 0L) {
        parts <- c(parts, paste(trailing, collapse = ", "))
    }
    result <- paste(parts, collapse = " ")

    if (susceptibility) {
        result <- paste("SUSCEPTIBILITY TO", result)
    }

    result
}


#' Fix Disease Capitalization (INTERNAL)
#'
#' Apply rules- and curation-based capitalization fixes to a lowercased disease
#' name.
#'
#' @param x A character vector of lowercased name strings.
#' @param eponyms A named character vector of case-insensitive whole-word
#'   substitutions applied after lowercasing, for proper noun (eponym)
#'   capitalization that cannot be determined automatically. Names are the
#'   target words (lowercase) and values are their replacements, e.g.
#'   `c("waardenburg" = "Waardenburg", "hirschsprung" = "Hirschsprung")`.
#'
#'   Pairs are applied in order using whole-word matching. Use `NULL` to disable
#'   all eponym correction.
#' @param patterns A named character vector of case-insensitive phrase-level
#'   regex substitutions applied to the whole lowercased string *after*
#'   `eponyms`. Names are regex patterns; values are their replacements, e.g.
#'   `c("short syndrome" = "SHORT syndrome")`.
#'
#'   Patterns are applied longest-first so more specific patterns take
#'   precedence. Phrase patterns override any conflicting word-level `eponyms`
#'   substitutions. Use `NULL` to disable.
#'
#' @returns A character vector with capitalization fixes applied.
#'
#' @section Capitalization rules applied automatically:
#' * Roman numerals following 'type ' (e.g. `type xi` → `type XI`).
#' * Alphanumeric subtype codes (e.g. `7a` → `7A`, `3a` → `3A`).
#' * Immunoglobulin abbreviations: `IgA`, `IgD`, `IgE`, `IgG`, `IgM`, `IgY`.
#'
#' @noRd
fix_disease_caps <- function(x, eponyms = NULL, patterns = NULL) {
    # Roman numeral reformatting
    out <- gsub(
        "\\b(type|syndrome|disease)\\s+([ivxlcdm]+)([a-z]{0,2})\\b",
        "\\1 \\U\\2\\3",
        x,
        perl = TRUE
    )

    # Alphanumeric subtype reformatting
    out <- gsub("\\b(\\d+)([a-z]{1,2})\\b", "\\1\\U\\2", out, perl = TRUE)
    # Immunoglobulin abbreviations: IgA, IgD, IgE, IgG, IgM, IgY
    out <- gsub(
        "\\big([aegmdy])\\b",
        "Ig\\U\\1",
        out,
        perl = TRUE,
        ignore.case = TRUE
    )

    # Single isolated letters: type designators, chromosome names, gene
    # symbols, etc. (e.g. "type a" -> "type A", "y-linked" -> "Y-linked")
    out <- gsub("\\b([a-z])\\b", "\\U\\1", out, perl = TRUE)

    # Word-level eponym replacements: single-pass via alternation + lookup —
    # avoids ~1000 sequential gsub calls on the full vector.
    if (!is.null(eponyms)) {
        ep_names_esc <- gsub(
            "([.+*?^${}()|\\[\\]\\\\])", "\\\\\\1",
            names(eponyms), perl = TRUE
        )
        alt_pat <- paste0("(?i)\\b(", paste(ep_names_esc, collapse = "|"), ")\\b")
        lookup  <- purrr::set_names(unname(eponyms), tolower(names(eponyms)))
        out <- stringr::str_replace_all(out, alt_pat, function(m) unname(lookup[tolower(m)]))
    }

    # Phrase-level pattern replacements, longest-first.
    # Replacements using PCRE case modifiers (\U, \L, \E) must use
    # gsub(perl=TRUE) without ignore.case; all others run case-insensitively.
    if (!is.null(patterns) && length(patterns) > 0L) {
        is_perl_case <- grepl("\\\\[ULE]", patterns)
        ord <- order(nchar(names(patterns)), decreasing = TRUE)
        for (i in ord) {
            out <- gsub(
                names(patterns)[[i]],
                patterns[[i]],
                out,
                ignore.case = !is_perl_case[[i]],
                perl = TRUE
            )
        }
    }

    out
}
