#' Prepare a ROBOT Template from Data
#'
#' Formats
#' @export
prep_robot_template <- function(data, save_to = NULL, ...) {
    UseMethod("prep_robot_template")
}

#' @export
prep_robot_template.onto_missing_list <- function(data, save_to = NULL, ...) {
    rt <- prep_robot_template(data$onto_missing_df, save_to = save_to, ...)
    attr(rt, "in_onto") <- data$in_onto
}

#' @export
prep_robot_template.onto_missing_df <- function(data, save_to = NULL, ...) {
    purrr::map(data, prep_robot_template)
}

#' @export
prep_robot_template.in_onto_df <- function(data, save_to = NULL, sheet = NULL) {
    purrr::map(data, prep_robot_template)
}


#' Save Data
#'
#' Saves data generated by `DO.utils` as Google Sheets, .csv, or .tsv file(s).
#' This is a generic function. Generally, data.frames will be saved directly to
#' one of these file types, while lists of data.frames will be saved as either
#' multiple sheets (Google Sheets) or multiple files (.csv/.tsv). For the latter
#' case, if data.frames are named the name will be appended before the
#' extension and, if not, a number will be added.
#'
#' @param data A single data object to save.
#' @param save_to The path/location to save to, as a string or something
#'     recognizable by [googlesheets4::as_sheets_id()].
#' @param ... Arguments passed on to methods.
#'
#' @export
save_data <- function(data, save_to, ...) {
    UseMethod("save_data")
}

#' @export
save_data.onto_missing_list <- function(data, save_to, create_rt = TRUE, ...) {

}

check_save_to <- function(save_to) {
    ext <- unique(tools::file_ext(save_to))
    if (ext %in% c("csv", "tsv")) {
        loc <- save_to
        attr(loc, "save_location") <- ext
    } else {
        rlang::check_installed("googlesheets4", reason = "to save data as a Google Sheet.")
        loc <- try(googlesheets4::as_sheets_id(save_to))

        if (class(loc)[1] == "try-error") {
            rlang::abort("`save_to` location could not be validated.")
        } else {
            attr(loc, "save_location") <- "gs"
        }
    }

    loc
}

